language: generic

keys:
  - SSH_KEY_FOR_SIGNING
  - TEST_SING_KEY2
  - TEST_PEM

env:
  global: IMAGE_NAME=test878/tagname:latest

before_install:
  - curl -LO https://github.com/sigstore/cosign/releases/download/v1.2.0/cosign-linux-amd64
  - chmod +x cosign-linux-amd64
  - sudo mv cosign-linux-amd64 /usr/local/bin/cosign
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

before_script:
  # - echo "$SSH_KEY_FOR_SIGNING" | base64 --decode > cosign.key
  # - chmod 600 cosign.key
  # - ls -l cosign.key
  # - echo $TEST_SING_KEY
  #- travis_key TEST_SING_KEY2 cosign_test.key
  # - travis_key SSH_KEY_FOR_SIGNING cosign.key
  # - cat cosign.key
   - travis_key TEST_PEM cosign_test.key
  # - echo "$TEST_PEM" | base64 --decode > cosign_test.key
  # - chmod 600 cosign_test.key
  

script:
  - docker pull $IMAGE_NAME # Pull the image to ensure it exists
  - cosign sign --key cosign_test.key $IMAGE_NAME # Sign the actual image

after_script:
  - docker logout
