language: generic

keys:
  - SSH_KEY_FOR_SIGNING


env:
  global:
    - IMAGE_NAME=test878/tagname:latest

before_install:
  - cosign version
  - curl -LO https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign-linux-amd64
  - chmod +x cosign-linux-amd64
  - sudo mv cosign-linux-amd64 /usr/local/bin/cosign
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cosign version

script:
  - docker pull $IMAGE_NAME # Pull the image to ensure it exists
  - yes | cosign sign --key cosign.key $IMAGE_NAME # Sign the actual image

after_script:
  - docker logout
