language: generic

before_install:
  - curl -LO https://github.com/sigstore/cosign/releases/download/v1.2.0/cosign-linux-amd64
  - chmod +x cosign-linux-amd64
  - sudo mv cosign-linux-amd64 /usr/local/bin/cosign
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

before_script:
  - echo "$SSH_KEY_FOR_SIGNING" | base64 --decode > cosign.key
  - chmod 600 cosign.key

script:
  - echo "This is a test artifact for Cosign signing." > test.txt
  - cosign sign --key cosign.key test.txt
